### ISSUE TITLE
"Last Change" Column not updated after editing with Only office

### ISSUE THREAD

**Issue by YannikG** [haiwen/seahub#1854]
I'm wondering why doesn't Seafile generate a new Version of a File when I'm editing this File in the Only Office Document Online Document Editor?  Seafile does also not update the "Last Change" Column in the View.

This Bug cause that the SeaDrive Client does not sync the Files.

Thanks for this great Product!

Hope this Bug get fixed soon

**Comment by shoeper** [comment]
Is this still the case?

**Comment by YannikG** [comment]
Could be. I am not using Seafile anymore.

**Comment by odontomachus** [comment]
This is due to the integration workflow.
OnlyOffice only saves the document to the backend when **all editing sessions are closed**. There is the same problem with NextCloud & OwnCloud's integrations. The temporary solution we have come up with for our project was to shorten the OnlyOffice editor session so that it "kicks" everyone out after a period of inactivity and saves the document. We found a session of about 10 minutes to work reasonably well, so long as users are aware of this limitation.

See: https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/116

Currently, enabling the force save option in OnlyOffice breaks the Seafile integration model for collaborative editing. Saving changes the version of the file, and that is used to build the OnlyOffice session url, so if a second user joins in after the first user has saved, she will be working on a different version of the document in a separate session.

I am working on an alternative model, but need to figure out the edge cases. Once that's done, I'll make a PR.
https://github.com/odontomachus/seahub/tree/feature_onlyoffice_path_based
