### ISSUE TITLE
Unable to log in post-upgrade

### ISSUE THREAD

**Issue by lazynooblet** [haiwen/seahub#187]
Upgraded from 2.1.4 to 3.0.2, now the administrator login no longer works on the web interface.

I can login and use seafile via the Windows client okay.

But the web GUI complains of incorrect password. Have reset the password via web interface and reset email, but same issue.

Nothing in logs. seahub.log has remained empty since original install, is there a switch somewhere?

Using FastCGI method with MySQL. Can login as other accounts ( I have tested 2 other non-admin accounts ).

**Comment by bogprs** [comment]
Hi. I just ran into the similar problem when upgrading from 2.1 to 4.3: 
no access to admin nor user accounts through web-portal.
Furthermore, I cannot figure out where is ccnet-db located (find and locate commands do not yield any result).

Thanks for you help.

Best,
Bogdan

**Comment by shoeper** [comment]
Did you run all upgrade scripts?

Furthermore you need to recreate all libraries because the format has been changed in 3.x.
If you don't want to loose any history you might have a look at forum.seafile-server-org. There is one user creating an upgrade script that you might be interested in (but I don't have the specific link)

**Comment by bogprs** [comment]
Yup - all the single one from my old version to the new one.
I will look into library format later - I need to gain again access to my account through web page.
N.B. Clients on mobile and PC seem to work perfectly - nevertheless, I cannot log in on a newly installed client.
