### ISSUE TITLE
 Massive Web UI performance issues on Raspberry Pi

### ISSUE THREAD

**Issue by jonashaag** [haiwen/seahub#252]
From https://github.com/haiwen/seafile/issues/736

On Raspberry Pi, it takes up to 30 seconds (clarification: most of the time it's around 4s) to load a simple repository overview page.

I did a little bit of profiling on this but couldn't find one single source of slowness. It's hard to profile performance, though, because 90% of the logic is in templates, not Python code, which are difficult to properly profile.

May I suggest that on long term, logic should be moved from templates into the views and models, which has the following benefits:
- It's the recommended programming style for Django
- It's easier to profile and optimize
- It's faster by multiple orders of magnitude

**Comment by Strayer** [comment]
I'm not entirely sure if this is already in the settings, but production sites can and should use the template cache provided by Django:
https://docs.djangoproject.com/en/1.5/ref/templates/api/#django.template.loaders.cached.Loader

I guess the increased memory usage would be minimal and this could help a lot on devices as slow as the raspberry pi.

**Comment by Strayer** [comment]
Another thing that came to my mind is running SeaHub with PyPy. As far as I can see, its a rather simple Django application without many dependencies. Could be quite easy to get it working with PyPy.

**Comment by shoeper** [comment]
And the advantage of pypy would be?

**Comment by Strayer** [comment]
If the slowdown experienced on the Raspberry Pi is actually caused due to the Python code and/or the template parsing, using PyPy as the interpreter for SeaHub *may* increase the overall performance.

In plain performance testing, Django runs faster on PyPy: http://speed.pypy.org/timeline/#/?exe=1&base=2+472&ben=django&env=1&revs=200&equid=off

Its worth a try in this specific setup, since PyPy is also preinstalled on Raspbian.

**Comment by freeplant** [comment]
This issue shoud have been fixed in the latest version.
