### ISSUE TITLE
[Feature] Date-based browsing in history

### ISSUE THREAD

**Issue by Fly0s** [haiwen/seahub#257]
Hi!

I want to submit an idea regarding history/snapshot browsing in the Seahub interface.

Right now, if one has to look at an ancient state of a library, one has to click on "History", then select the maximum of 100 per page, and click "Next", "Next", "Next" while surveying the displayed dates to reach the period one wants. This, obviously, can take quite a long time.

Now, having a maximum of 100 per page is not that a bad default, as it is not too heavy on the server and bandwidth.

However, since the server is readily able to display the date of each event and snapshot, I'll have to assume that this information is stocked somewhere, and that it would somehow be possible to search the history using the date information.

Thus, here's my feature proposal: when accessing history, a date field is displayed, which allows to directly goes to events correspond to, say, the 26th of January 2013, instead of clicking "Next", "Next"... for a long time.

By the way, thanks for the good job on Seafile! I was already a great piece of software, and becoming more and more awesome! ;)

**Comment by moritzschaefer** [comment]
Workaround is not working for me. It seems the value is hard coded to 100. 
It turns out that the low level RPC from the server doesn't support ordering. In my opinion the only proper way to implement this is to add support for this is implement proper ordering in the seafile RPC (https://github.com/haiwen/seafile/blob/master/server/repo-perm.c, function seaf_repo_manager_list_dir_with_perm) so the API has the possibility to call the RPC with a filtering argument. 

I will work on this in https://github.com/moritzschaefer/seafile and make a pullrequest to haiwen/seafile as soon as it's done. after that it's quite simple to adjust the seahub ajax call. 

Unfortunately adding a sort argument to the RPC call would break the API, as the server doesn't use default arguments and as such it seems that it will be necessary to add another RPC call. 

Please elaborate on this, as I might be wrong on some points.

**Comment by moritzschaefer** [comment]
https://github.com/haiwen/seafile/issues/1464

**Comment by moritzschaefer** [comment]
As it might take a very long time to accept the issue and a related pullrequest in haiwen/seafile, I think it's a good idea to implement filtering on the client side first by pulling all contents and sorting them on the client side.
While it would be slower for directories with many files, it's definitely a better solution than what is implemented right now (sorting only the files being locally loaded).
As far as I know, this is done in seadroid.

Would such a pull request be accepted?

**Comment by freeplant** [comment]
Only very few people need such feature, we will not implement it. If the situation is changed in the future, one can reopen the issue.
