### ISSUE TITLE
Creation date 1970-01-01 pretty silly

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seahub#333]
Hi there,
I read somewhere you optimized the file view in seahub by not showing the real creation date but '1970-01-01' instead. I think this is pretty wrong - just looks like a bug. Either remove the date completely or, which I would prefer, just show the real date as before. Maybe make it an option to be set in seahub_settings.py? But this current way just is waste of space and nerves.
Thanks and regards

**Comment by freeplant** [comment]
It's only for old libraries.

**Comment by HenriWahl** [comment]
But confusing anyways - even if users use Seafile happily for a while and thus definitefly have some old libraries. Why should they create new libraries to get real creation dates? Can't this behaviour be just an option - if necessary at all?

**Comment by freeplant** [comment]
There are several features that old libraries can't support like syncing via HTTP protocol. Let's view it as a necessary investment into the future. And I'd like to keep code clean without so much options and branches.

**Comment by shoeper** [comment]
Wouldn't it be the best to make a tool to convert old libraries, to be fully compatible with newer versions?

**Comment by languitar** [comment]
Definitely, a migration path is needed here. Otherwise you have to recreate libraries over and over again on every format change.

**Comment by freeplant** [comment]
The old format is designed when we don't have much experience with the problem.  As far as I can see, we will not introduce new format in the future.

**Comment by languitar** [comment]
Still, for some libraries I wouldn't even want to lose the history that has accumulated.

**Comment by HenriWahl** [comment]
There was a conversion tool for old-style to version-3-style libraries - why not for version-4-style libraries?

**Comment by HenriWahl** [comment]
Wasn't there some tool to convert V2 to V3?

**Comment by HenriWahl** [comment]
No way to convert libraries or offer an option to show the correct creation date for those who need it?

**Comment by lins05** [comment]
When ugprading from seafile server 2.x to 3.x, the "migration" only changed
the layout of seafile data, and the data content is not changed.

In contrast, the format change introduced in seafile server 3.1 is more
fundamental (from a custom binary format to json). I don't think  it's
possible to do some "conversion" from old format to the new format so that
the old libraries can upgrade to the new data format.

It MAY BE possible to create a migration tool, so that one can create a new
library and import the old library into the new one. But the only benefit
after that is the history of the library is kept. However, the user would
still need to unsync the old library and resync with the new one. Besides,
it may took quite some time to implement such a tool correctly.

So the suggested way is to create a new library and copy all the files of
the old library into it, then resync with the new one on all seafile
clients.

**Comment by HenriWahl** [comment]
OK, sounds like a major shift... but why is it so hard to display the change/creation time? Even as option? I really fear major confusion for our otherwise quite happy Seafile users.

**Comment by freeplant** [comment]
I admit it is a wrong decision to not keep the compatibility by showing the time as "1970-01-01". But since the decision is already made and the code is done. Let's stay with it.

**Comment by languitar** [comment]
Maybe something like "unavailable" would be better to not confuse users. And a tooltip that explains the situation.

**Comment by freeplant** [comment]
@languitar Thanks for the suggestion.

**Comment by HenriWahl** [comment]
Hi,
this time just a question: is there an easy way to find all v2 style libraries to be able to inform the users about necessary steps to convert them?
Thanks and regards

**Comment by freeplant** [comment]
I'm sorry no such tool yet.

**Comment by HenriWahl** [comment]
If there is no tool - is there a way how I can find out on filesystem level on seafile server which library is affected?
I use https://github.com/HenriWahl/seafadm to get a list of all libraries. The resulting list I want to use to see which of the libraries is a v2 one.

**Comment by shoeper** [comment]
Just an idea: I think since v4 timestamps are also shown in fuse. You could 
mount seafile somewhere and check which libraries contain mostly files and 
folder with a bad creation date. Afaik also emails are shown when you mount 
via fuse so your script could also directly notify them (or at least you 
could easily at the end of the process).


Am 6. März 2015 10:57:46 schrieb HenriWahl <notifications@github.com>:

**Comment by HenriWahl** [comment]
Sounds interesting - thanks!

**Comment by freeplant** [comment]
@shoeper Thanks!

**Comment by linuxturtle** [comment]
Markus Germeier has create a bash script which will query the sqlite database for each repo for version information.  He believes that "0" (i.e. no version info) means the repo was created with v2, and "1' means it was created with v3 and later.

https://groups.google.com/d/msg/seafile/f_hPE-SVXLo/IkZgu5-y4RoJ

I'll echo everyone else that this is a major pain in the butt.  I mean, I've accumulated over 100GB in one library, and re-uploading that over a slow DSL connection to create the new library is going to take a week or more.

**Comment by shoeper** [comment]
@linuxturtle do you have the server unter control?`
Then try mounting it via fuse and install the command line client to sync the content to a new library. Once finished you can delete the old one and rename the new one. Then you sync the new one with the existing folder on your PC. Should be finished within a few ours. Maybe the sync process on the server needs one or two days but that's way better than a few weeks for dsl upload.

**Comment by linuxturtle** [comment]
@shoeper Thank you for the suggestion.  Yes, I do control the server, and that's a good idea if I have enough disk space on the instance to duplicate the whole library twice (it's a hosted VPS with very limited CPU/memory, but lots of storage).  Still a pain in the butt, but not as painful as doing everything over a DSL connection :)
