### ISSUE TITLE
feature request: video player fullscreen

### ISSUE THREAD

**Issue by shoeper** [haiwen/seahub#659]
Please add a fullscreen mode to the integrated video player.

**Comment by jbbr** [comment]
I'm using Google Chrome 45 (dev) and Seafile 4.2.3 - I got a working fullscreen button.
![seafile_fullscreen_video](https://cloud.githubusercontent.com/assets/682607/8267601/2edb6434-1769-11e5-96ca-bb2518f5a60e.png)

In Firefox I'm unable to play the same video - and I'm not seeing a fullscreen button. I assume this is because of differences in codec support for HTML5 videos.

**Comment by shoeper** [comment]
Interesting, using 4.2 Pro edition with Chrome (not dev) on Android and Windows did not show the button for me.

**Comment by shoeper** [comment]
It is there.
